name: forex_currency_conversion
description: A Flutter Package for real-time forex prices and conversions.
version: 0.9.1
repository: https://github.com/Macacoazul01/forex_currency_conversion

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
